### ISSUE TITLE
Has this package been abandoned?

### ISSUE THREAD

**Issue by JustSteveKing** [MagicTheGathering/mtg-sdk-php#11]
I found this sdk and thought it was cool, but it seems a little inactive - has it been abandoned at all?

**Comment by guiwoda** [comment]
This is not actively maintained anymore, at least not by me. I don't know the status of the `MagicTheGathering` org to be honest.

**Comment by JustSteveKing** [comment]
@guiwoda I'd be interested in attempting an updated version as long as nobody else minds?

**Comment by guiwoda** [comment]
I'd talk with @adback03 or @jregnier

**Comment by jregnier** [comment]
I only maintain the .net version so not sure about this one sorry.

**Comment by adback03** [comment]
@guiwoda @JustSteveKing I can add you as a project contributor if you'd like. As far as the status of the project goes, I am working with mtgjson folks on providing a newer version of the API. Don't have an ETA yet, but the project is not abandoned.

**Comment by JustSteveKing** [comment]
@adback03 more than happy to join in on the project!!

**Comment by JustSteveKing** [comment]
@adback03 I'm in! I'm also on the Discord too, so will monitor there. Would love a chance to catch up on plans for upgrades 🙂
