### ISSUE TITLE
get sets by specific type

### ISSUE THREAD

**Issue by AndrewKoliaka** [MagicTheGathering/mtg-sdk-php#2]
how to get sets by type?
`Set::where(['type' => 'core'])->all()`returns all sets in game, not only core sets

**Comment by adback03** [comment]
This is currently not supported by the API. I will get an update out tonight to support filtering on set type.

**Comment by adback03** [comment]
This has been resolved with version 1.16.4 of the API.

https://github.com/MagicTheGathering/mtg-api/blob/master/CHANGELOG.md
