### ISSUE TITLE
Get All Set Codes of Paper only?

### ISSUE THREAD

**Issue by lmjamie** [MagicTheGathering/mtg-sdk-php#4]
I am trying to use your API, but you have very little-to-no documentation on what functions are available and how to do things
I need to get all of the set codes of all non-online only sets. So far I can find no ability to return the codes, I will try just getting the set and see if I can get the code from there. But I cannot seem to filter out the onlineOnly sets.
I type:
`Set::where(["onlineOnly" => false])->all();`
but it still returns the ones where onlineOnly is true. How am I supposed to do this?

**Comment by guiwoda** [comment]
Hi @lmjamie!
This sdk is a wrapper around http://magicthegathering.io/ API. If it's not there, you can't do it. So the `onlineOnly` parameter doesn't exist (it's a field of the response, not a query parameter), you'd have to download the sets and dump them into a database for a query like that.

Feel free to PR any changes you find necessary to current docs.
