### ISSUE TITLE
Card::all() only returns 100 cards

### ISSUE THREAD

**Issue by rossjcooper** [MagicTheGathering/mtg-sdk-php#9]
I'm trying to fetch all the cards using `Card:all()` which understandable takes a while but it only seems to ever return 100 results. I have tried setting the `pageSize` greater than 100 in a `where()` function but this seems to make no difference.

**Comment by guiwoda** [comment]
This is a limitation in the API. There's nothing you can do on the SDK side, you'll have to fetch them by batches.

**Comment by rossjcooper** [comment]
Ok I did see that in the API docs but the README to this SDK is misleading as it uses 1000 pageSize as examples.

**Comment by guiwoda** [comment]
I'll change that! Thanks for the heads up.
